{{ if (include "project.createService" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.serviceName" . }}
  namespace : {{ include "project.namespace" . }}
  labels: {{- include "project.standardLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "project.tplvaluesRender" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "project.tplvaluesRender" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- include "project.tplvaluesRender" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "project.tplvaluesRender" ( dict "value" .Values.service.sessionAffinityConfig "context" $ ) | nindent 4 }}
  {{- end }}
  ports:
    - name: {{ include "project.tplvaluesRender" ( dict "value" .Values.service.name "context" $ ) }}
      protocol: TCP
      port: {{ include "project.tplvaluesRender" ( dict "value" .Values.service.port "context" $ ) }}
      targetPort: {{ include "project.tplvaluesRender" ( dict "value" .Values.service.targetPort "context" $ ) }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.type }}
      nodePort: {{ include "project.tplvaluesRender" ( dict "value" .Values.service.nodePort "context" $ ) }}
      {{- end }}
  selector: {{- include "project.matchLabels" . | nindent 4 }}
{{- end }}