{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s23daimgmlm.serviceAccountName" . }}
  namespace : {{ include "s23daimgmlm.namespace" . }}
  labels: {{- include "s23daimgmlm.standardLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "s23daimgmlm.tplvaluesRender" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "s23daimgmlm.tplvaluesRender" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- include "s23daimgmlm.tplvaluesRender" ( dict "value" .Values.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}