apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: jenkins
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - jenkinsg1.rikkei.org
      secretName: jenkins-tls
  rules:
    - host: jenkinsg1.rikkei.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: thanhtai18021994@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
 namespace: cert-manager
spec:
 acme:
   # The ACME server URL
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: thanhtai18021994@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-staging
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert
  namespace: jenkins
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: testdg1.rikkei.org
  dnsNames:
  - testdg1.rikkei.org       
---
apiVersion: v1
kind: Ingrees
metadata:
  name: nexus-ingress
  namespace: jenkins
spec:
  tls:
      - hosts:
          - testdg1.rikkei.org
        secretName: tls-secret
  rules:
    - host: testdg1.rikkei.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus3
                port:
                  number: 8081   
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: nexus-ingress
    namespace: jenkins
  spec:
    ingressClassName: nginx
    rules:
      - host: testdg1.rikkei.org
        http:
          paths:
            - backend:
                service:
                  name: nexus3
                  port:
                    number: 8081
              path: /
              pathType: Prefix
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - jenkinsdg1.rikkei.org
          secretName: tls-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - smpfeclient.vietnamfmc.site
      secretName: smpfeclient.vietnamfmc.site
  rules:
    - host: smpfeclient.vietnamfmc.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 80
---
                  
            