apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
  namespace: hieuns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kube.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - mongodb.vietnamfmc.site
      secretName: mongodb.vietnamfmc.site
  rules:
    - host: mongodb.vietnamfmc.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongodb
                port:
                  number: 27017