apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-proxy
  namespace: np
spec:
  selector:
    matchLabels:
      app: be-proxy
  template:
    metadata:
      labels:
        app: be-proxy
    spec:
      
      containers:
      - name: be-proxy
        image: nexusrepo.rikkei.org/np/dev/be/be-proxy:v1
        resources: {}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: be-proxy
  namespace: np
spec:
  selector:
    app: be-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: be-proxy
  namespace: np
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $2
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: np-dev.rikkei.org
    http:
      paths:
      - path: /api/v1/(.*)
        pathType: Prefix
        backend:
          service:
            name: be-proxy
            port:
              number: 80
  tls:
  - hosts:
    - np-dev.rikkei.org
    secretName: np-dev-rikkei-org-tls

