apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.nameOverride }}-{{ .Values.env }}
    tier: {{ .Values.env }}-backend
  annotations:
    reloader.stakater.com/auto: "true"
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    rollme: {{ randAlphaNum 5 | quote }}
  name: {{ .Values.nameOverride }}
  namespace : {{ .Values.namespace }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}-{{ .Values.env }}
      tier: {{ .Values.env }}-backend
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}-{{ .Values.env }}
        tier: {{ .Values.env }}-backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: {{ .Values.nameOverride }}-{{ .Values.env }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # {"$imagepolicy": "flux-system:b22dadtubac-be-apigateway"}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ .Values.service.nameHttp }}
          protocol: TCP            
          containerPort: {{ .Values.service.targetPortHttp }}
        volumeMounts:
          - name: {{ .Values.nameOverride }}-{{ .Values.env }}-krakend
            mountPath: /etc/krakend/krakend.json
            subPath: krakend.staging.json
            readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        {{- if .Values.command }}
        command:
          {{- toYaml .Values.command | nindent 10 }}
        {{- end }}
        
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}

        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}
      volumes:
      - name: {{ .Values.nameOverride }}-{{ .Values.env }}-krakend
        configMap:
          name: {{ .Values.nameOverride }}-{{ .Values.env }}

      restartPolicy: {{ .Values.restartPolicy }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.nameOverride }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}