apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-job
  namespace: s22nbaeqxeca-prelive
spec:
  schedule: 59 22 * * *
  timeZone: Asia/Ho_Chi_Minh
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: scale-up-job
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - '-c'
                - >-
                  kubectl scale deployment -n s22nbaeqxeca-prelive --replicas
                  2 --all 
              resources: {}
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
