---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uat-user
  namespace: b22dadtubac-uat-cloud  
---
apiVersion: v1
kind: Secret
metadata:
  name: uat-token
  namespace: b22dadtubac-uat-cloud  
  annotations:
    kubernetes.io/service-account.name: uat-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hola2-dev
  name: uat-role
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smp-uat
  namespace: smp-uat  # Replace with the desired namespace
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uat-role-binding
  namespace: b22dadtubac-dev-cloud
subjects:
- kind: ServiceAccount
  name: uat-user
  namespace: b22dadtubac-uat-cloud
roleRef:
  kind: Role
  name: uat-role
  apiGroup: rbac.authorization.k8s.io
