apiVersion: v1
kind: Pod
metadata:
  name: ubuntu3
  namespace: b22dadtubac-dev-cloud
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-secret-.env: cleo/dev2/store
    vault.hashicorp.com/agent-inject-template-.env: |
      {{- with secret "cleo/dev2/store" -}}    
      {{- range $k, $v := .Data }}
      {{ $k }}={{ $v }} 
      {{- end }}
      {{- end }} 
    vault.hashicorp.com/role: cleo-dev2
    vault.hashicorp.com/auth-path: auth/kubernetes
spec:
  serviceAccountName: vault-dev
  containers:
  - name: ubuntu
    image: ubuntu
    command:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m" 
---
# while read LINE; do export $LINE; done < "/vault/secrets/.env"        