apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-{{ .Values.env }}
  namespace : {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.configMapData }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}