env:
  - name: "TZ"
    value: "Asia/Ho_Chi_Minh"
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On
        HC_Errors_Count 4
        HC_Retry_Failure_Count 4
        HC_Period 30
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*b22dadtubac-*.log
        multiline.parser docker, cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On
        Ignore_Older 7d
        Exclude_Path *.gz,*.zip,*.tar
        Read_from_Head False
        Rotate_Wait 10
        Skip_Empty_Lines on
        Refresh_Interval  10
        Buffer_Chunk_Size 32KB
        Buffer_Max_Size   32KB

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           Off
        Merge_Log_Key       log_processed
        Merge_Log_Trim      On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Keep_Log            On
        Labels              Off
        Annotations         Off      
        Buffer_Size         0  
    [Filter]
        Name    nest
        Match    kube.*
        Operation    lift
        Nested_under    kubernetes
        Add_prefix    kubernetes_
    [Filter]
        Name    modify
        Match    kube.*
        Remove    stream
        Remove    kubernetes_pod_id
        Remove    kubernetes_host
        Remove    kubernetes_container_hash
        Remove    kubernetes_docker_id
        Remove    kubernetes_container_image
    [Filter]
        Name    nest
        Match    kube.*
        Operation    nest
        Wildcard    kubernetes_*
        Nest_under    kubernetes
        Remove_prefix    kubernetes_
  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master-headless.logging.svc
        Port            9200
        HTTP_User       elastic
        HTTP_Passwd     Cl30P@ssAdm1n2023
        Time_Key        @timestamp
        Logstash_Format           On
        Logstash_Prefix           pod_name
        Logstash_Prefix_Separator -
        Logstash_DateFormat       %Y.%m.%d
        Replace_Dots    On
        Trace_Error On
        Suppress_Type_Name On
        Retry_Limit     False
        Type  _doc
        Buffer_Size 2MB
  upstream: {}
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L    
  extraFiles: 
    labelmap.json: |
      {
        "kubernetes": {
          "container_name": "container",
          "namespace_name": "namespace",
          "pod_name": "instance"
        }
      }