env:
  - name: "TZ"
    value: "Asia/Ho_Chi_Minh"
daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlog
    hostPath:
      path: /var/log      
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File
  - name: cert
    persistentVolumeClaim:
      claimName: fluentbit-agent-pv      

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true
  - name: cert
    mountPath: /etc/cert
    readOnly: true
config:    
  inputs: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On
          HC_Errors_Count 4
          HC_Retry_Failure_Count 4
          HC_Period 30

      [INPUT]
          Name              tail
          Tag               kube.*
          Path              /var/log/containers/*.log
          multiline.parser docker, cri
          DB                /var/log/flb_kube.db
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On
          Ignore_Older 7d
          Exclude_Path *.gz,*.zip,*.tar
          Read_from_Head False
          Rotate_Wait 10
          Skip_Empty_Lines on
          Refresh_Interval  10
          Buffer_Chunk_Size 32KB
          Buffer_Max_Size   32KB

      [FILTER]
          Name                kubernetes
          Match               kube.*
          Kube_URL            https://kubernetes.default.svc:443
          Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix     kube.var.log.containers.
          Merge_Log           Off
          Merge_Log_Key       log_processed
          Merge_Log_Trim      On
          K8S-Logging.Parser  On
          K8S-Logging.Exclude On
          Keep_Log            On
          Labels              Off
          Annotations         Off      
          Buffer_Size         0  
      [Filter]
          Name    nest
          Match    kube.*
          Operation    lift
          Nested_under    kubernetes
          Add_prefix    kubernetes_
      [Filter]
          Name    modify
          Match    kube.*
          Remove    stream
          Remove    kubernetes_pod_id
          Remove    kubernetes_host
          Remove    kubernetes_container_hash
          Remove    kubernetes_docker_id
          Remove    kubernetes_container_image
      [Filter]
          Name    nest
          Match    kube.*
          Operation    nest
          Wildcard    kubernetes_*
          Nest_under    kubernetes
          Remove_prefix    kubernetes_

      [OUTPUT]
          Name            es
          Match           kube.*
          Host            10.20.23.196
          Port            9200
          HTTP_User       elastic
          HTTP_Passwd     5D77+f4ca8k7g5Niv0GJ
          Time_Key        @timestamp
          Logstash_Format           On
          Logstash_Prefix           pod_name
          Logstash_Prefix_Separator -
          Logstash_DateFormat       %Y.%m.%d
          Replace_Dots    On
          Trace_Error On
          Suppress_Type_Name On
          Retry_Limit     False
          Type  _doc
          Buffer_Size 512M
          tls On
          tls.verify Off
          tls.ca_file /etc/cert/http_ca.crt
